### ISSUE TITLE
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/vue-dapp.js?v=ba5590db' does not provide an export named 'MetaMaskConnector'

### ISSUE THREAD

**Issue by xpenh** [chnejohnson/vue3-dapp-starter#2]
Hi, thank you for this open source project. I downloaded it. Now I have a problem in the process of executing the code. I have no idea,
package.json:
{
  "name": "vue3-dapp-starter",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "serve": "vite preview"
  },
  "dependencies": {
    "buffer": "^6.0.3",
    "ethers": "^5.5.2",
    "jiti": "^1.13.0",
    "process": "^0.11.10",
    "util": "^0.12.4",
    "vue": "^3.2.2",
    "vue-dapp": "^0.5.2",
    "vue-router": "4"
  },
  "devDependencies": {
    "@rollup/plugin-inject": "^4.0.4",
    "@vitejs/plugin-vue": "^2.3.3",
    "typescript": "^4.5.4",
    "vite": "^2.9.9",
    "vite-plugin-windicss": "^1.8.4",
    "windicss": "^3.1.8"
  }
}

<img width="990" alt="image" src="https://user-images.githubusercontent.com/22676892/170957443-dd73c3dd-40bb-4ef2-bbf2-7b6498547c2c.png">

**Comment by chnejohnson** [comment]
@xpenh Hmm...sounds strange, it works fine on my computer and also on Netlify.

**Comment by xpenh** [comment]
Thanks a lot . I will test with vite@2.6.0.
